### ISSUE TITLE
NoMethodError render_for_api with rails 5 api app

### ISSUE THREAD

**Issue by goravbhootra** [fabrik42/acts_as_api#104]
Hi,

While using the gem in Rails 5 app create with --api flag, wherein application controller inherits from ActionController::API, following error is encountered:
```NoMethodError (undefined method `render_for_api' for #<MembersController:0x007fecd4286fe0>```

Changing 
```class ApplicationController < ActionController::API``` to 
```class ApplicationController < ActionController::Base``` fixes the issue as a workaround

**Comment by fabrik42** [comment]
Hi, 
thank you for reporting this, I will have a look at it! :)

**Comment by fabrik42** [comment]
Hi,

I looked into this issue. As you are using the api-only version of Rails, you don't want to change the parent class of your `ApplicationController`. This would introduce a lot of overhead that you are trying to avoid using the api-only version.

But, the helper methods for rendering API responses rely on the `ActionController::Base` class being loaded. So I think the best solution is to include the helper method in the controller manually:

Just add this line to the top of your `ApplicationController`:

```ruby
include ActsAsApi::Rendering
```

then you should be able to inherit from `ActionController:API` again!


Cheers,

Christian

**Comment by goravbhootra** [comment]
Hi Christian,

Thank you for the response.

I cannot submit PR for updating the documentation on Wiki page. It will be a good idea to mention this in docs - it might help others.

Cheers and thank you for this great gem!

Gorav

**Comment by fabrik42** [comment]
Hi Gorav,

sorry for the delay. I think it's a good idea to add it to the wiki. Here is the first version:
https://github.com/fabrik42/acts_as_api/issues/104

Let me know what you think!

Best,
Christian

**Comment by goravbhootra** [comment]
Hi Christian,

> One solution is to include the helper methods in the controller manually

suggest changing above line to:
Suggested solution is to manually include the helper methods in the controller or include it in ApplicationController if you need it in multiple controllers (or something to that effect)

Rest looks good to me.

Cheers,
Gorav

**Comment by fabrik42** [comment]
Very good! I updated the article!

**Comment by fabrik42** [comment]
I will close this issue for now. Please reopen it if there is any new information. :)
