### ISSUE TITLE
Use current_user variable in template ?

### ISSUE THREAD

**Issue by rnaud** [fabrik42/acts_as_api#33]
Hello,

I'm trying to get around the best way to add session data to my templates.

For instance, my user1 is requesting the profile of user2 with the user http://domain/users/2.json

My template looks like something like that : 

  api_accessible :default do |t|
    t.add :id
    t.add :name
    t.add :avatar_image
    t.add lambda{|u| u.following?(current_user)}, :as => :following
  end

But the current_user variable is not available in the model. Is there a way around that with the current implementation of the gem ?

Thanks for your help !

**Comment by anquegi** [comment]
I have a similar problem, but I want to limit the number of child associations in a template .i.e.

the limit would be a param. in the request if not present default value of 10


```
  api_accessible :v1_list do |template|
    binding.pry
    template.add :id
    template.add :parent_id
    template.add :client_id
    template.add :reference
    template.add :created_at
    template.add :updated_at
    template.add :closed_at
    template.add :subtype_id
    template.add :state
    template.add lambda{ |incident| incident.items.first(limit) }, :template => :v1_list, :as => :items
  end
```

So how can I add this, must I use presenter?, or I have any alternatives

**Comment by fabrik42** [comment]
Hi! You can pass options to `as_api_response`, see [these examples](https://github.com/fabrik42/acts_as_api/blob/874ccfbcd5efcd90b6b56ec126b07c053675901e/spec/support/model_examples/options.rb).

They will get passed as the second argument to all lambdas.

So in your case it would work like this:

```ruby
  MyModel.api_accessible :v1_list do |template|
    binding.pry
    template.add :id
    template.add :parent_id
    template.add :client_id
    template.add :reference
    template.add :created_at
    template.add :updated_at
    template.add :closed_at
    template.add :subtype_id
    template.add :state
    template.add lambda{ |incident, options| incident.items.first(options[:limit]) }, :template => :v1_list, :as => :items
  end

  MyModel.as_api_response(:v1_list, limit: 10)
```

I hope this helps!
